sandbox:
  development:
    adapter: <%= CONFIG['sandbox']['development']['database']['adapter'] %>
    host: <%= CONFIG['sandbox']['development']['database']['host'] %>
    port: <%= CONFIG['sandbox']['development']['database']['port'] %>
    database: <%= CONFIG['sandbox']['development']['database']['name'] %>
    user: <%= CONFIG['sandbox']['development']['database']['user'] %>
    password: <%= CONFIG['sandbox']['development']['database']['password'] %>
    pool: 5
    timeout: 5000
  production:
    adapter: <%= CONFIG['sandbox']['production']['database']['adapter'] %>
    host: <%= CONFIG['sandbox']['production']['database']['host'] %>
    port: <%= CONFIG['sandbox']['production']['database']['port'] %>
    database: <%= CONFIG['sandbox']['production']['database']['name'] %>
    user: <%= CONFIG['sandbox']['production']['database']['user'] %>
    password: <%= CONFIG['sandbox']['production']['database']['password'] %>
    pool: <%= CONFIG['database']['pool'] %>
    timeout: 5000

development:
  adapter: <%= CONFIG['database']['adapter'] %>
  host: <%= CONFIG['database']['host'] %>
  port: <%= CONFIG['database']['port'] %>
  database: <%= CONFIG['database']['name'] %>
  user: <%= CONFIG['database']['user'] %>
  password: <%= CONFIG['database']['password'] %>
  pool: <%= CONFIG['database']['pool'] %>
  timeout: 5000

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: <%= CONFIG['database']['adapter'] %>
  host: <%= CONFIG['database']['host'] %>
  port: <%= CONFIG['database']['port'] %>
  database: <%= CONFIG['database']['name'] %>
  user: <%= CONFIG['database']['user'] %>
  password: <%= CONFIG['database']['password'] %>
  pool: <%= CONFIG['database']['pool'] %>
  timeout: 5000

staging:
  adapter: <%= CONFIG['database']['adapter'] %>
  host: <%= CONFIG['database']['host'] %>
  port: <%= CONFIG['database']['port'] %>
  database: <%= CONFIG['database']['name'] %>
  user: <%= CONFIG['database']['user'] %>
  password: <%= CONFIG['database']['password'] %>
  pool: <%= CONFIG['database']['pool'] %>
  timeout: 5000

production:
  adapter: <%= CONFIG['database']['adapter'] %>
  host: <%= CONFIG['database']['host'] %>
  port: <%= CONFIG['database']['port'] %>
  database: <%= CONFIG['database']['name'] %>
  user: <%= CONFIG['database']['user'] %>
  password: <%= CONFIG['database']['password'] %>
  pool: <%= CONFIG['database']['pool'] %>
  timeout: 5000
